version: '3.7'

services:

  on_comment:
    build: .
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn --workers=3 on_comment.wsgi -b 0.0.0.0:8080"
    depends_on:
      - postgres
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - proxy


  postgres:
    image: postgres:12.0
    environment:
      POSTGRES_PASSWORD: den_u
      POSTGRES_USER: den
      POSTGRES_DB: den_bd
    ports:
      - 5432:5432
    networks:
      - proxy
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  celery:
    build: .
    command: celery -A routines worker -B -l info
    depends_on:
      - postgres
      - redis
    networks:
      - proxy
    restart: always

  redis:
    hostname: redis
    image: redis:alpine
    networks:
      - proxy


networks:
  proxy:
    driver: bridge


volumes:
  postgres_data: