version: '3.9'

services:

  on_comment:
    build: .
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn --workers=3 on_comment.wsgi -b 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - postgres


  postgres:
    image: postgres:12.0
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: tester
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  celery:
    build: .
    command: celery -A routines worker -B -l info
    depends_on:
      - redis
  redis:
    hostname: redis
    image: redis:alpine

  chrome:
    image: selenium/node-chrome:4.0.0-beta-2-prerelease-20210312
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"

  selenium-hub:
    image: selenium/hub:4.0.0-beta-2-prerelease-20210312
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"