version: '3.7'

services:

  on_comment:
    build: .
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn --workers=3 on_comment.wsgi -b 0.0.0.0:8080"
    depends_on:
      - postgres
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - proxy


  postgres:
    image: postgres:12.0
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: tester
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - proxy
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  celery:
    build: .
    command: celery -A routines worker -B -l info
    depends_on:
      - postgres
      - redis
      - chrome
      - selenium-hub
    networks:
      - proxy
    restart: always

  redis:
    hostname: redis
    image: redis:alpine
    networks:
      - proxy

  chrome:
    image: selenium/node-chrome:4.0.0-beta-2-prerelease-20210312
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"
    networks:
      - proxy
    restart: always

  selenium-hub:
    image: selenium/hub:4.0.0-beta-2-prerelease-20210312
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - proxy
    restart: always

networks:
  proxy:
    driver: bridge


volumes:
  postgres_data: