# Generated by Django 3.1.7 on 2021-02-26 18:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('post_date', models.IntegerField()),
                ('news_img_link', models.URLField()),
                ('news_link', models.URLField()),
                ('news_text', models.TextField(max_length=300)),
                ('top_comment', models.TextField(max_length=300)),
                ('news_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='api.newstag')),
            ],
        ),
    ]
