# Generated by Django 3.1.7 on 2021-02-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_img_link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='post_date',
            field=models.IntegerField(default=0),
        ),
    ]
