# Generated by Django 3.1.7 on 2021-02-26 18:29

from django.db import migrations, models

from ..models import NewsTag


def add_new_tag(*args):
    NewsTag.objects.create(tag_name='people')
    NewsTag.objects.create(tag_name='auto')
    NewsTag.objects.create(tag_name='tech')
    NewsTag.objects.create(tag_name='realt')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210226_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstag',
            name='tag_name',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.RunPython(add_new_tag)
    ]
