# Generated by Django 3.1.7 on 2021-03-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_newstag_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='post_date',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
